# Generated by Django 4.1.2 on 2022-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZachetDB', '0002_alter_securities_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securities',
            name='id',
        ),
        migrations.AlterField(
            model_name='securities',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
