# Generated by Django 4.1.2 on 2022-10-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZachetDB', '0003_remove_securities_id_alter_securities_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('secur_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ZachetDB.securities')),
            ],
        ),
    ]
